### PR TITLE
IOS-4769: Removed extensionHours from v2/search/extension_rates/ endpoint

### PR DESCRIPTION
**Pull request by acmaciek**
**Issue Link**
[IOS-4769](https://spothero.atlassian.net/browse/IOS-4769)

**Description**
Removed extensionHours from v2/search/extension_rates/ endpoint

[IOS-4769]: https://spothero.atlassian.net/browse/IOS-4769?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by delannoyk — DISMISSED** [review]
Looks good, but can you add a bit of context as to why we're removing it?

**Review by MartinJrP — APPROVED** [review]

**Comment by acmaciek** [comment]
@delannoyk 
I spoke with SUnghwan and he told me we no longer need to attach this parameter. The server will send the multiple response if applicable

**Comment by delannoyk** [comment]
When I tried to run a request without it, it fails though. @acmaciek @jodeng2 are we sure this isn't required?

**Comment by jodeng2** [comment]
> When I tried to run a request without it, it fails though. @acmaciek @jodeng2 are we sure this isn't required?

@amitc005 is working on removing this field. After he is done with that, I think we are good. Thanks for checking!

**Comment by amitc005** [comment]
@delannoyk @acmaciek wait for my signal, I think I should be done by tomorrow morning.

**Comment by amitc005** [comment]
@delannoyk @acmaciek you guys are good with removing extension hours

**Comment by delannoyk** [comment]
@acmaciek can you add context to the latest changes as well (non-optional > optional)

**Review by delannoyk — APPROVED** [review]

**Pull request merged**
